#ifndef IOCTL_H
#define IOCTL_H

#define OUICHEFS_IOC_MAGIC 'M'
#define USED_BLOCKS _IOR(OUICHEFS_IOC_MAGIC, 1, int)
#define PARTIAL_BLOCKS _IOR(OUICHEFS_IOC_MAGIC, 2, int)
#define INTERNAL_FRAG _IOR(OUICHEFS_IOC_MAGIC, 3, int)
#define USED_BLOCKS_INFO _IOR(OUICHEFS_IOC_MAGIC, 4, int)
#define DEFRAG _IOR(OUICHEFS_IOC_MAGIC, 5, int)

#endif
